---
  - name: Instalación LAMP
    hosts: lamp
    serial: 1
    gather_facts: false
    tasks:
      - name: Instalar LAMP
        include_role:
          name: lamp

  - name: Instalación MDADM
    hosts: git
    gather_facts: false
    tasks:
      - name: Instalar MDADM
        include_role:
          name: mdadm

  - name: Instalación Git
    hosts: git
    tasks:
      - name: Instalar Git
        include_role:
          name: git

  - name: Instalación GitList
    hosts: git
    gather_facts: false
    tasks:
      - name: Instalar GitList
        include_role:
          name: gitlist

  - name: Instalación OpenLdap
    hosts: ldap
    tasks:
      - name: Instalar OpenLdap
        include_role:
          name: ldap
...
