---
  - name: Crear usuario git
    user:
      name: git
      comment: Usuario para propositos de Git
      shell: "{{gitshell}}"
      home: "{{githome}}"

  - name: Agregar automontaje del RAID al fstab y montarlo como home de Git
    mount:
      name: "{{githome}}"
      src: /dev/md0
      fstype: ext4
      state: mounted
      opts: defaults,nofail,discard

  - name: Crear repositorio de prueba
    command: "git init {{repodir}}"

  - name: Añadir pruebas
    file:
      path: "{{repodir}}/{{repofiletest}}"
      state: touch
      group: git
      owner: git

  - name: Añadir README.md.j2
    template:
      src: install.md.j2
      dest: "{{repodir}}/README.md"

  - name: Añadir texto a pruebas
    lineinfile:
      dest: "{{repodir}}/{{repofiletest}}"
      line: "Hola mundo"

  - name: Git add
    command: git add --all
    args:
      chdir: "{{repodir}}"

  - name: Git conf mail
    git_config:
      name: user.email
      repo: "{{repodir}}"
      scope: global
      value: 'git@developers.local'

  - name: Git conf name
    git_config:
      name: user.name
      repo: "{{repodir}}"
      scope: global
      value: 'git'

  - name: Cambiar el comentario del repositorio
    lineinfile:
      dest: "{{repodir}}/.git/description"
      regexp: "^Unnamed repository"
      line:
        Repositorio de prueba post-instalación

  - name: Prueba commit para el repositorio de muestra
    command: git commit -m 'Prueba primer repo'
    args:
      chdir: "{{repodir}}"

  - name: Crear servicio para iniciar el demonio de git
    template:
      src: daemon.j2
      dest: "/etc/init.d/dgit"
      mode: '766'

  - name: Configurar tamaño de /run para el correcto registro deool servicio dgit
    shell: mount -t tmpfs tmpfs /run -o remount,size=85M

  - name: Registrar servicio dgit
    shell: update-rc.d dgit "{{ item }}"
    with_items:
      - "defaults"
      - "enable"

  - name: Iniciar el servicio dgit
    service:
      name: dgit
      enabled: yes
      state: started

  - name: Acceso público al repositorio
    file:
      path: "{{repodir}}/.git/git-daemon-export-ok"
      state: touch

  - name: Reconfigurar propietario de la carpeta git y su contenido
    file:
      path: "{{githome}}"
      owner: git
      group: git
      recurse: yes
...
